# Generated by Django 5.2 on 2025-04-14 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagingstudy', '0002_initial'),
        ('practitionerroles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagingstudyseriesperformeractorreference',
            name='practitioner_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='imaging_study_series_performer_reference', to='practitionerroles.practitionerrole'),
        ),
    ]
