
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-20T02:32:55+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "875aa3d53281b83a205442db83ac41ddf817ef9a",
 "version": "1.5.dev2516"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
