
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-19T07:59:51+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "75517c8997bdfd65a1604dcc2a4838b81772f9b3",
 "version": "2.6.0rc5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
