max_raw_data_days = 14
typical_tracked_events =['MV_COMMISSIONED','PLANT_COMMISSIONED','DATA_LOSS','DATA_LOSS_COP','EQUIPMENT_MALFUNCTION','ALARM',
    'INSTALLATION_ERROR','PARTIAL_OCCUPANCY','INSTALLATION_ERROR_COP','SOO_PERIOD','SOO_PERIOD_COP','SYSTEM_MAINTENANCE']