# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tast/cros/services/cros/inputs/keyboard_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tast/cros/services/cros/inputs/keyboard_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5tast/cros/services/cros/inputs/keyboard_service.proto\x12\x10tast.cros.inputs\x1a\x1bgoogle/protobuf/empty.proto\"\x1a\n\x0bTypeRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1b\n\x0c\x41\x63\x63\x65lRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\" \n\x11\x41\x63\x63\x65lPressRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\"\n\x13\x41\x63\x63\x65lReleaseRequest\x12\x0b\n\x03key\x18\x01 \x01(\t2\xb3\x02\n\x0fKeyboardService\x12?\n\x04Type\x12\x1d.tast.cros.inputs.TypeRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x41\n\x05\x41\x63\x63\x65l\x12\x1e.tast.cros.inputs.AccelRequest\x1a\x16.google.protobuf.Empty\"\x00\x12K\n\nAccelPress\x12#.tast.cros.inputs.AccelPressRequest\x1a\x16.google.protobuf.Empty\"\x00\x12O\n\x0c\x41\x63\x63\x65lRelease\x12%.tast.cros.inputs.AccelReleaseRequest\x1a\x16.google.protobuf.Empty\"\x00\x42\x36Z4go.chromium.org/tast-tests/cros/services/cros/inputsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tast.cros.services.cros.inputs.keyboard_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4go.chromium.org/tast-tests/cros/services/cros/inputs'
  _globals['_TYPEREQUEST']._serialized_start=104
  _globals['_TYPEREQUEST']._serialized_end=130
  _globals['_ACCELREQUEST']._serialized_start=132
  _globals['_ACCELREQUEST']._serialized_end=159
  _globals['_ACCELPRESSREQUEST']._serialized_start=161
  _globals['_ACCELPRESSREQUEST']._serialized_end=193
  _globals['_ACCELRELEASEREQUEST']._serialized_start=195
  _globals['_ACCELRELEASEREQUEST']._serialized_end=229
  _globals['_KEYBOARDSERVICE']._serialized_start=232
  _globals['_KEYBOARDSERVICE']._serialized_end=539
# @@protoc_insertion_point(module_scope)
