from .storage_connection_parameters import StorageConnectionParameters as StorageConnectionParameters
from _typeshed import Incomplete
from typing import Any

class B2Client:
    storage_connection_parameters: Incomplete
    def __init__(self, storage_connection_parameters: StorageConnectionParameters) -> None: ...
    def upload_existing_file(self, file_path: str, file_name: str | None = None) -> dict[str, Any]: ...
    def upload_zipped_jsoned_string(self, data: str, file_name: str) -> None: ...
    def shutdown(self) -> None: ...
