# Generated by Django 5.2 on 2025-04-17 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimresponses', '0004_initial'),
        ('devicerequests', '0003_initial'),
        ('explanationofbenefits', '0004_initial'),
        ('supplyrequests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanationofbenefit',
            name='claim_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='explanation_of_benefits_claim_response', to='claimresponses.claimresponsereference'),
        ),
        migrations.AddField(
            model_name='explanationofbenefititemrequestreference',
            name='device_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='explanation_of_benefit_item_request_reference_device_request', to='devicerequests.devicerequest'),
        ),
        migrations.AddField(
            model_name='explanationofbenefititemrequestreference',
            name='supply_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='explanation_of_benefit_item_request_reference_supply_request', to='supplyrequests.supplyrequest'),
        ),
    ]
