# Generated by Django 4.2.20 on 2025-04-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_mileagerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
