def levenshtein_distance(s1: str, s2: str) -> int: ...
def ocr_weighted_levenshtein_distance(s1: str, s2: str) -> float: ...
def custom_weighted_levenshtein_distance(
    s1: str, 
    s2: str, 
    cost_map: dict[tuple[str, str], float], 
    default_cost: float | None = None
) -> float: ...
