from typing import Tuple

LOREM_IPSUM_WORDS: str
LOREM_IPSUM_SENTENCES: str
LOREM_IPSUM_PARAGRAPHS: str

SEPARATOR_WHITESPACE: str
SEPARATOR_ESCAPE: str
SEPARATOR_NEWLINE: str
SEPARATOR_NEWLINE_AND_BREAK: Tuple[str, int]