class FontSize: pass
class FontType: pass
class CornerRoundness: pass
class TextColor: pass
class GrayTextColor: pass
class ButtonColor: pass
class ButtonHoverColor: pass
class SwitchColor: pass
class SwitchKnobColor: pass
class SwitchHoverColor: pass
class SwitchEnabledColor: pass
class SwitchEnabledHoverColor: pass
class InputColor: pass
class InputHoverColor: pass
class InputThemeColor: pass
class DropdownColor: pass
class DropdownHoverColor: pass
class PopupAnimationDuration: pass
class PopupShowDuration: pass
class PopupColor: pass
class PopupOutlineColor: pass
class PopupProgressBarColor: pass