# Generated by Django 4.2.20 on 2025-04-20 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_transaction_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice_numb',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='qty',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
