
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-22T13:29:43-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e27ba9dc2a64d9eacf3b2e1ab7b79df5e9875343",
 "version": "2025.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
