# Generated by Django 5.2 on 2025-04-14 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionorders', '0003_initial'),
        ('practitionerroles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionorderperformerreference',
            name='practitioner_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrition_order_performer_reference_practitioner_role', to='practitionerroles.practitionerrole'),
        ),
    ]
