from __future__ import annotations
from .service import MaleoMetadataServiceGeneralParametersTransfers

class MaleoMetadataGeneralParametersTransfers:
    Service = MaleoMetadataServiceGeneralParametersTransfers