from __future__ import annotations
from .service import MaleoMetadataServiceServiceParametersTransfers

class MaleoMetadataServiceParametersTransfers:
    Service = MaleoMetadataServiceServiceParametersTransfers