"""scripts [`Module`]."""

from typing import Iterable

def generateLocationHTML_() -> str: ...
def generateWindowsCommand_(url: str) -> Iterable[str]: ...
def generateWindowsCommand_2_(url: str) -> Iterable[str]: ...
def generateMacosxCommand_(url: str) -> str: ...
