class console:
    @staticmethod
    def log(*args: object, **kwargs: object) -> None: ...

class System:
    class out:
        @staticmethod
        def println(*args: object, **kwargs: object) -> None: ...

class Console:
    @staticmethod
    def WriteLine(*args: object, **kwargs: object) -> None: ...

def echo(*args: object, **kwargs: object) -> None: ...
def sh_echo(*args: object, **kwargs: object) -> None: ...
def println(*args: object, **kwargs: object) -> None: ...
def puts(*args: object, **kwargs: object) -> None: ...
def println_rust(*args: object, **kwargs: object) -> None: ...
class fmt:
    @staticmethod
    def Println(*args: object, **kwargs: object) -> None: ...
