# Generated by Django 5.2 on 2025-04-16 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimresponses', '0005_claimresponseadditemrequestreference_device_request_and_more'),
        ('contracts', '0003_contractfriendlycontentreferencereference_document_reference_and_more'),
        ('coverages', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverage',
            name='contract',
            field=models.ManyToManyField(blank=True, related_name='coverage_contract', to='contracts.contractreference'),
        ),
        migrations.AddField(
            model_name='coverageclaimresponsereference',
            name='claim_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coverage_claim_response_reference_claim_response', to='claimresponses.claimresponse'),
        ),
    ]
