# coding: utf-8

"""
    Sureel API

    API for the Sureel network.

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.analysis_history_entry_request_data_any_of_controlnet_conditioning_scale import AnalysisHistoryEntryRequestDataAnyOfControlnetConditioningScale
from typing import Optional, Set
from typing_extensions import Self

class AnalysisHistoryEntryRequestDataAnyOfControlnet(BaseModel):
    """
    AnalysisHistoryEntryRequestDataAnyOfControlnet
    """ # noqa: E501
    conditioning_scale: Optional[AnalysisHistoryEntryRequestDataAnyOfControlnetConditioningScale] = None
    guidance_start: Optional[Union[StrictFloat, StrictInt]] = None
    guidance_end: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["conditioning_scale", "guidance_start", "guidance_end"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnalysisHistoryEntryRequestDataAnyOfControlnet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of conditioning_scale
        if self.conditioning_scale:
            _dict['conditioning_scale'] = self.conditioning_scale.to_dict()
        # set to None if conditioning_scale (nullable) is None
        # and model_fields_set contains the field
        if self.conditioning_scale is None and "conditioning_scale" in self.model_fields_set:
            _dict['conditioning_scale'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnalysisHistoryEntryRequestDataAnyOfControlnet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "conditioning_scale": AnalysisHistoryEntryRequestDataAnyOfControlnetConditioningScale.from_dict(obj["conditioning_scale"]) if obj.get("conditioning_scale") is not None else None,
            "guidance_start": obj.get("guidance_start"),
            "guidance_end": obj.get("guidance_end")
        })
        return _obj


