# coding: utf-8

"""
    Sureel API

    API for the Sureel network.

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GetStylePresets200Response(BaseModel):
    """
    GetStylePresets200Response
    """ # noqa: E501
    painting: Optional[Any] = Field(alias="Painting")
    digital_art: Optional[Any] = Field(alias="Digital Art")
    photography: Optional[Any] = Field(alias="Photography")
    anime: Optional[Any] = Field(alias="Anime")
    __properties: ClassVar[List[str]] = ["Painting", "Digital Art", "Photography", "Anime"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetStylePresets200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if painting (nullable) is None
        # and model_fields_set contains the field
        if self.painting is None and "painting" in self.model_fields_set:
            _dict['Painting'] = None

        # set to None if digital_art (nullable) is None
        # and model_fields_set contains the field
        if self.digital_art is None and "digital_art" in self.model_fields_set:
            _dict['Digital Art'] = None

        # set to None if photography (nullable) is None
        # and model_fields_set contains the field
        if self.photography is None and "photography" in self.model_fields_set:
            _dict['Photography'] = None

        # set to None if anime (nullable) is None
        # and model_fields_set contains the field
        if self.anime is None and "anime" in self.model_fields_set:
            _dict['Anime'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetStylePresets200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Painting": obj.get("Painting"),
            "Digital Art": obj.get("Digital Art"),
            "Photography": obj.get("Photography"),
            "Anime": obj.get("Anime")
        })
        return _obj


