"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from uai_annotation_requests import utils
from uai_annotation_requests.types import BaseModel


class AnnotationRequestExportNotReadyDTOData(BaseModel):
    message: str


class AnnotationRequestExportNotReadyDTO(Exception):
    r"""A message providing details on why the annotations
    export is not available.
    """

    data: AnnotationRequestExportNotReadyDTOData

    def __init__(self, data: AnnotationRequestExportNotReadyDTOData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, AnnotationRequestExportNotReadyDTOData)
