
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-19T20:32:22+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "ee8d025e1c046b22b3b148e5e97c0e107c979ee3",
 "version": "1.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
