# coding: utf-8

"""
    Sureel API

    API for the Sureel network.

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.inpaint_request import InpaintRequest

class TestInpaintRequest(unittest.TestCase):
    """InpaintRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InpaintRequest:
        """Test InpaintRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InpaintRequest`
        """
        model = InpaintRequest()
        if include_optional:
            return InpaintRequest(
                prompt = '',
                content_image_path = '',
                mask_image_path = '',
                creative_inpainting = True,
                negative_prompt = '',
                apply_watermark = True,
                custom_watermark = '',
                style_preset = '',
                artist_preset = [
                    openapi_client.models._v1_ai_audio_ldm_text_to_artist_audio_post_request_artist_preset_inner._v1_ai_audio_ldm_text_to_artist_audio_post_request_artistPreset_inner(
                        collection_uuid = '', 
                        preset_attribution = 0, )
                    ],
                upscale = None,
                inference_steps = 10,
                cfg = 0,
                seed = -2147483648,
                strength = None,
                generate_attribution = True,
                batch_size = 1,
                remove_bg = True,
                generate_preview = True,
                webhook = ''
            )
        else:
            return InpaintRequest(
                prompt = '',
                content_image_path = '',
                mask_image_path = '',
        )
        """

    def testInpaintRequest(self):
        """Test InpaintRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
