
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-23T14:36:16+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "81e52afc86008aaf84a0d8d2fe4a2783e25cc6a4",
 "version": "0.16.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
