# Generated by Django 5.2 on 2025-04-16 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalimpressions', '0004_clinicalimpressionfindingitemreference_document_reference'),
        ('conditions', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionstageassessmentreference',
            name='clinical_impression',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='condition_stage_assessment_reference_clinical_impression', to='clinicalimpressions.clinicalimpression'),
        ),
    ]
