import enum


class EnvironNames(enum.StrEnum):
    LOGGING_FILE = "LOGGING_FILE"
    LOGGING_JSONL = "LOGGING_JSONL"
    RICH_FILE_CONSOLE_WIDTH = "RICH_FILE_CONSOLE_WIDTH"


LOGGING_FILE = EnvironNames.LOGGING_FILE
LOGGING_JSONL = EnvironNames.LOGGING_JSONL
RICH_FILE_CONSOLE_WIDTH = EnvironNames.RICH_FILE_CONSOLE_WIDTH
