# Generated by Django 5.1.4 on 2025-01-17 14:47

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menubuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=modelcluster.fields.ParentalKey(blank=True, help_text='Set a parent menu item to create a dropdown.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menubuilder.menuitem'),
        ),
    ]
