EZ_CUSTOM_LABELS = {
    'LABEL_CARRIER_DEFAULT': '0',
    'LABEL_CUSTOM_DEFAULT': '1',
    'LABEL_CUSTOM_INVOICE_PLUS_LBL_LANDSCAPE': '2',
    'LABEL_CUSTOM_INVOICE_PLUS_LBL_POTRAIT': '3',
    'LABEL_CUSTOM_4x6': '4',
    'LABEL_CUSTOM_4x3': '5',
    'LABEL_CUSTOM_4x3_B2B_POD_LABEL': '6',
    'LABEL_CUSTOM_B2B_DOCKET': '7',
}

VENDOR_NAMES = {
    'xpressbees_b2b_cargo': 'XpressBees Cargo'
}
