# Generated by Django 5.1.1 on 2024-10-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artd_partner", "0007_position_partner"),
        ("artd_siigo", "0004_warehouse"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Warehouse",
            new_name="SiigoWarehouse",
        ),
        migrations.AlterModelOptions(
            name="siigowarehouse",
            options={
                "verbose_name": "Siigo Catalog Warehouse",
                "verbose_name_plural": "Siigo Catalog Warehouses",
            },
        ),
    ]
