# Generated by Django 5.1.1 on 2024-10-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artd_siigo", "0016_siigoproductpricelist_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siigoproduct",
            name="json_data",
            field=models.JSONField(
                blank=True,
                help_text="JSON data for the product",
                null=True,
                verbose_name="JSON Data",
            ),
        ),
    ]
