# Generated by Django 5.1.1 on 2024-10-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artd_siigo", "0017_siigoproduct_json_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siigoproduct",
            name="prices",
            field=models.ManyToManyField(
                blank=True,
                help_text="Prices for the product",
                to="artd_siigo.siigoproductprice",
                verbose_name="Prices",
            ),
        ),
        migrations.AlterField(
            model_name="siigoproduct",
            name="taxes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Taxes for the product",
                to="artd_siigo.siigotax",
                verbose_name="Taxes",
            ),
        ),
    ]
