# Generated by Django 5.1.1 on 2024-10-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artd_siigo", "0027_citymapping_countrymapping_regionmapping"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="citymapping",
            options={
                "verbose_name": "Mapping City",
                "verbose_name_plural": "Mappings Cities",
            },
        ),
        migrations.AlterModelOptions(
            name="countrymapping",
            options={
                "verbose_name": "Mapping Country",
                "verbose_name_plural": "Mapping Countries",
            },
        ),
        migrations.AlterModelOptions(
            name="regionmapping",
            options={
                "verbose_name": "Mappin Region",
                "verbose_name_plural": "Mapping Regions",
            },
        ),
    ]
