# Generated by Django 5.1.1 on 2024-10-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artd_siigo", "0032_siigoconfig_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siigoconfig",
            name="address",
            field=models.JSONField(default=dict, verbose_name="Address"),
        ),
    ]
