# Generated by Django 5.1.1 on 2025-03-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artd_siigo", "0063_siigoorderinvoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="siigoorderinvoice",
            name="json_data",
            field=models.JSONField(default=dict, verbose_name="JSON Data"),
        ),
    ]
