# Generated by Django 5.1.1 on 2025-03-24 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artd_partner", "0010_partner_signed_key"),
        ("artd_siigo", "0075_alter_siigoorderinvoice_invoice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siigoinvoice",
            name="additional_fields",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Additional Fields"
            ),
        ),
        migrations.AlterField(
            model_name="siigoinvoice",
            name="balance",
            field=models.FloatField(blank=True, null=True, verbose_name="Balance"),
        ),
        migrations.AlterField(
            model_name="siigoinvoice",
            name="cost_center",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Cost Center"
            ),
        ),
        migrations.AlterField(
            model_name="siigoinvoice",
            name="currency",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Currency"
            ),
        ),
        migrations.AlterField(
            model_name="siigoinvoice",
            name="customer",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Customer"
            ),
        ),
        migrations.AlterField(
            model_name="siigoinvoice",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="siigoinvoice",
            name="global_discounts",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Global Discounts"
            ),
        ),
        migrations.AlterField(
            model_name="siigoinvoice",
            name="items",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Items"
            ),
        ),
        migrations.AlterField(
            model_name="siigoinvoice",
            name="json_data",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="JSON Data"
            ),
        ),
        migrations.AlterField(
            model_name="siigoinvoice",
            name="mail",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Mail"
            ),
        ),
        migrations.AlterField(
            model_name="siigoinvoice",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Metadata"
            ),
        ),
        migrations.AlterField(
            model_name="siigoinvoice",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="siigoinvoice",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="artd_partner.partner",
                verbose_name="Partner",
            ),
        ),
        migrations.AlterField(
            model_name="siigoinvoice",
            name="payments",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Payments"
            ),
        ),
        migrations.AlterField(
            model_name="siigoinvoice",
            name="seller",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Seller"
            ),
        ),
        migrations.AlterField(
            model_name="siigoinvoice",
            name="siigo_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Siigo ID"
            ),
        ),
        migrations.AlterField(
            model_name="siigoinvoice",
            name="stamp",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Stamp"
            ),
        ),
        migrations.AlterField(
            model_name="siigoinvoice",
            name="total",
            field=models.FloatField(blank=True, null=True, verbose_name="Total"),
        ),
    ]
