# This is awkward, I may rework this in the future.

AGKYRA                  : str = "Εκδόσεις Άγκυρα"
AIGOKEROS               : str = "Εκδόσεις Αιγόκερως"
ALEXANDRIA              : str = "Εκδόσεις Αλεξάνδρεια"
ALTER_EGO               : str = "Alter Ego (πρώην Δ.Ο.Λ.)"
ANATOLIKOS              : str = "Εκδόσεις Ανατολικός"
ASINI                   : str = "Εκδόσεις Ασίνη"
EIKOSTOU_PROTOU         : str = "Εκδόσεις του Εικοστού Πρώτου"
EMPEIRIA                : str = "Εμπειρία Εκδοτική"
# There is some connection between Ethnos and Panepistimiakes Kritis which I haven't figured out yet.
ETHNOS                  : str = "Έθνος"
FISHBOWL                : str = "Fishbowl Music Tank"
GUTENBERG               : str = "Εκδόσεις Gutenberg"
IANOS                   : str = "Εκδόσεις Ιανός"
LIVANI                  : str = "Εκδοτικός Οργανισμός Λιβάνη"
MEDUSA_SELAS            : str = "Μέδουσα-Σέλας Εκδοτική"
MENANDROS               : str = "Εκδόσεις Μένανδρος"
METRONOMOS              : str = "Εκδόσεις Μετρονόμος"
MYRTOS                  : str = "Εκδόσεις Μύρτος"  # a.k.a. Τίτος Αντύπας
MUSEUM_TUSCULANUM       : str = "Museum Tusculanum Press"
NEFELI                  : str = "Εκδόσεις Νεφέλη"
NTEFI                   : str = "Εκδόσεις Ντέφι"
OGDOO                   : str = "Εκδόσεις Όγδοο"
OPERA                   : str = "Εκδόσεις Opera"
PANEPISTIMIAKES_KRITIS  : str = "Πανεπιστημιακές Εκδόσεις Κρήτης"
PAPAZISI                : str = "Εκδόσεις Παπαζήση"
PATAKI                  : str = "Εκδόσεις Πατάκη"
SELF_PUBLISHED          : str = "Self Published"
STOCHASTIS              : str = "Εκδόσεις Στοχαστής"
SYGCHRONOI_EPOCHI       : str = "Σύγχρονοι Εποχή Εκδοτική"
SYGCHRONOI_ORIZONTES    : str = "Εκδόσεις Σύγχρονοι Ορίζοντες"
TOUBIS                  : str = "Εκδόσεις Τουμπής"
VIVLIOPELAGOS           : str = "Εκδόσεις Βιβλιοπέλαγος"
