# Generated by Django 4.2.20 on 2025-04-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardOperatingProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('takeoff', 'Takeoff'), ('landing', 'Landing'), ('maneuver', 'Maneuvers'), ('emergency', 'Emergency Procedures'), ('other', 'Other')], max_length=50)),
                ('procedure', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
