def set_epsilon(eps: float) -> None: ...
def get_epsilon() -> float: ...

class __MetaEpsilon(type):
    @property
    def eps(cls) -> float: ...

class epsilon(metaclass=__MetaEpsilon):
    def __init__(self, eps: float) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, exc_traceback: types.TracebackType | None) -> None: ...
    @classmethod
    def reset(cls) -> None: ...
