# Generated by Django 5.2 on 2025-04-14 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EncounterReason',
            new_name='AppointmentEncounterReason',
        ),
    ]
