from __future__ import annotations
from .organization_type import MaleoMetadataOrganizationTypeGeneralTypes

class MaleoMetadataGeneralTypes:
    OrganizationType = MaleoMetadataOrganizationTypeGeneralTypes