# coding: utf-8

"""
    Sureel API

    API for the Sureel network.

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.attribution1_values_inner import Attribution1ValuesInner

class TestAttribution1ValuesInner(unittest.TestCase):
    """Attribution1ValuesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Attribution1ValuesInner:
        """Test Attribution1ValuesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Attribution1ValuesInner`
        """
        model = Attribution1ValuesInner()
        if include_optional:
            return Attribution1ValuesInner(
                artist = '',
                value = 1.337,
                values = [
                    1.337
                    ],
                username = '',
                collection_name = '',
                collection_uuid = '',
                track_name = ''
            )
        else:
            return Attribution1ValuesInner(
                artist = '',
        )
        """

    def testAttribution1ValuesInner(self):
        """Test Attribution1ValuesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
