# coding: utf-8

"""
    Sureel API

    API for the Sureel network.

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_ai_ldm_cover_art_post_request import V1AiLdmCoverArtPostRequest

class TestV1AiLdmCoverArtPostRequest(unittest.TestCase):
    """V1AiLdmCoverArtPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1AiLdmCoverArtPostRequest:
        """Test V1AiLdmCoverArtPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1AiLdmCoverArtPostRequest`
        """
        model = V1AiLdmCoverArtPostRequest()
        if include_optional:
            return V1AiLdmCoverArtPostRequest(
                frame = None,
                text_first_line = '',
                text_second_line = '',
                font_first_line = None,
                font_second_line = None,
                font_color_first_line = [
                    0
                    ],
                font_color_second_line = [
                    0
                    ],
                cover_content = '',
                cover_style = '',
                cover_color_scheme = '',
                album_genre = '',
                album_seasonality = '',
                reference_cover_art = [
                    openapi_client.models.style_image.StyleImage(
                        style_image_path = '', 
                        style_image_weight = null, )
                    ],
                song_titles = '',
                song_path = '',
                lyrics = '',
                description_weight = None,
                negative_prompt = '',
                apply_watermark = True,
                custom_watermark = '',
                upscale = None,
                inference_steps = 10,
                cfg = 0,
                seed = -2147483648,
                generate_attribution = True,
                batch_size = 1,
                remove_bg = True,
                generate_preview = True,
                webhook = ''
            )
        else:
            return V1AiLdmCoverArtPostRequest(
                cover_content = '',
                cover_style = '',
                reference_cover_art = [
                    openapi_client.models.style_image.StyleImage(
                        style_image_path = '', 
                        style_image_weight = null, )
                    ],
        )
        """

    def testV1AiLdmCoverArtPostRequest(self):
        """Test V1AiLdmCoverArtPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
