
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-20T09:18:49-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "4bda2874669399db2c37d0a4bf6ae10e324d96a7",
 "version": "1.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
