
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-23T11:23:34+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "33a1743ece05ca5d9368e273faacb0e9451b7ed0",
 "version": "2.0.0-alpha.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
