# Generated by Django 5.2 on 2025-04-14 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentreferences', '0004_initial'),
        ('practitionerroles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentreferenceattesterpartyreference',
            name='practitioner_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_reference_attester_party_reference_practitioner_role', to='practitionerroles.practitionerrole'),
        ),
        migrations.AlterField(
            model_name='documentreferenceauthorreference',
            name='practitioner_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_reference_author_reference_practitioner_role', to='practitionerroles.practitionerrole'),
        ),
    ]
