# Generated by Django 5.2 on 2025-04-16 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodystructures', '0002_initial'),
        ('claims', '0005_claiminsurance_coverage_and_more'),
        ('contracts', '0003_contractfriendlycontentreferencereference_document_reference_and_more'),
        ('coverageeligibilityrequests', '0003_coverageeligibilityrequestinsurance_coverage'),
        ('devicerequests', '0004_devicerequest_code'),
        ('documentreferences', '0004_initial'),
        ('enrollmentrequests', '0002_initial'),
        ('immunizationrecommendations', '0002_initial'),
        ('supplyrequests', '0001_initial'),
        ('visionprescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreference',
            name='body_site',
            field=models.ManyToManyField(blank=True, related_name='document_reference_body_sites', to='bodystructures.bodystructurecodeablereference'),
        ),
        migrations.AddField(
            model_name='documentreferencebasedonreference',
            name='claim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_reference_based_on_reference_claim', to='claims.claim'),
        ),
        migrations.AddField(
            model_name='documentreferencebasedonreference',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_reference_based_on_reference_contract', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='documentreferencebasedonreference',
            name='coverage_eligibility_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_reference_based_on_reference_coverage_eligibility_request', to='coverageeligibilityrequests.coverageeligibilityrequest'),
        ),
        migrations.AddField(
            model_name='documentreferencebasedonreference',
            name='device_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_reference_based_on_reference_device_request', to='devicerequests.devicerequest'),
        ),
        migrations.AddField(
            model_name='documentreferencebasedonreference',
            name='enrollment_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_reference_based_on_reference_enrollment_request', to='enrollmentrequests.enrollmentrequest'),
        ),
        migrations.AddField(
            model_name='documentreferencebasedonreference',
            name='immunization_recommendation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_reference_based_on_reference_immunization_recommendation', to='immunizationrecommendations.immunizationrecommendation'),
        ),
        migrations.AddField(
            model_name='documentreferencebasedonreference',
            name='supply_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_reference_based_on_reference_supply_request', to='supplyrequests.supplyrequest'),
        ),
        migrations.AddField(
            model_name='documentreferencebasedonreference',
            name='vision_prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_reference_based_on_reference_vision_prescription', to='visionprescriptions.visionprescription'),
        ),
    ]
