# Generated by Django 4.2.20 on 2025-04-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_standardoperatingprocedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOPDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='sop_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='standardoperatingprocedure',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='droneincidentreport',
            name='damage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='droneincidentreport',
            name='emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='droneincidentreport',
            name='faa_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='droneincidentreport',
            name='injuries',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='droneincidentreport',
            name='witnesses',
            field=models.BooleanField(default=False),
        ),
    ]
