# Generated by Django 4.2.20 on 2025-04-18 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0005_alter_generaldocument_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StandardOperatingProcedure',
        ),
    ]
