# Generated by Django 4.2.20 on 2025-04-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0006_delete_standardoperatingprocedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Drone', 'Drone'), ('Battery', 'Battery'), ('Controller', 'Controller'), ('Payload', 'Payload'), ('Other', 'Other')], max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('faa_number', models.CharField(blank=True, max_length=50)),
                ('purchase_date', models.DateField()),
                ('firmware_version', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
