from artd_siigo.admin.base import *  # noqa
from artd_siigo.admin.catalogs import *  # noqa
from artd_siigo.admin.products import *  # noqa
from artd_siigo.admin.customers import *  # noqa
from artd_siigo.admin.mapping import *  # noqa
from artd_siigo.admin.configs import *  # noqa
from artd_siigo.admin.bills import *  # noqa
from artd_siigo.admin.import_progress import *  # noqa
from artd_siigo.admin.catalogs import *  # noqa
