# Generated by Django 5.2 on 2025-04-16 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimresponses', '0004_initial'),
        ('devicerequests', '0003_initial'),
        ('supplyrequests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimresponseadditemrequestreference',
            name='device_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_request_reference_device_request', to='devicerequests.devicerequest'),
        ),
        migrations.AddField(
            model_name='claimresponseadditemrequestreference',
            name='supply_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_response_add_item_request_reference_supply_request', to='supplyrequests.supplyrequest'),
        ),
    ]
