# Generated by Django 5.2 on 2025-04-16 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverseevents', '0007_initial'),
        ('deviceusages', '0002_initial'),
        ('documentreferences', '0004_initial'),
        ('immunizations', '0003_initial'),
        ('medicationstatements', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverseeventcontributingfactorreference',
            name='device_usage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverse_event_contributing_factor_reference_device_usage', to='deviceusages.deviceusage'),
        ),
        migrations.AddField(
            model_name='adverseeventcontributingfactorreference',
            name='document_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverse_event_contributing_factor_reference_document_reference', to='documentreferences.documentreference'),
        ),
        migrations.AddField(
            model_name='adverseeventcontributingfactorreference',
            name='immunization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverse_event_contributing_factor_reference_immunization', to='immunizations.immunization'),
        ),
        migrations.AddField(
            model_name='adverseeventcontributingfactorreference',
            name='medication_statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverse_event_contributing_factor_reference_medication_statement', to='medicationstatements.medicationstatement'),
        ),
        migrations.AddField(
            model_name='adverseeventmitigatingactionreference',
            name='document_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverse_event_mitigating_action_reference_document_reference', to='documentreferences.documentreference'),
        ),
        migrations.AddField(
            model_name='adverseeventpreventiveactionreference',
            name='document_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverse_event_preventive_action_reference_document_reference', to='documentreferences.documentreference'),
        ),
        migrations.AddField(
            model_name='adverseeventpreventiveactionreference',
            name='immunization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverse_event_preventive_action_reference_immunization', to='immunizations.immunization'),
        ),
        migrations.AddField(
            model_name='adverseeventsupportinginforeference',
            name='document_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverse_event_supporting_info_reference_document_reference', to='documentreferences.documentreference'),
        ),
        migrations.AddField(
            model_name='adverseeventsupportinginforeference',
            name='immunization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverse_event_supporting_info_reference_immunization', to='immunizations.immunization'),
        ),
        migrations.AddField(
            model_name='adverseeventsupportinginforeference',
            name='medication_statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverse_event_supporting_info_reference_medication_statement', to='medicationstatements.medicationstatement'),
        ),
        migrations.AddField(
            model_name='adverseeventsuspectentityinstancereference',
            name='immunization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverse_event_suspect_entity_instance_reference_immunization', to='immunizations.immunization'),
        ),
        migrations.AddField(
            model_name='adverseeventsuspectentityinstancereference',
            name='medication_statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverse_event_suspect_entity_instance_reference_medication_statement', to='medicationstatements.medicationstatement'),
        ),
    ]
