
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-18T10:46:02-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "f0925c85c2baa114ed179e00d845529357edc955",
 "version": "0.4.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
