# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fewsats-logger-py',
                'doc_host': 'https://Fewsats.github.io',
                'git_url': 'https://github.com/Fewsats/fewsats-logger-py',
                'lib_path': 'fewsats_logger'},
  'syms': {'fewsats_logger.core': {'fewsats_logger.core.setup_logging': ('core.html#setup_logging', 'fewsats_logger/core.py')}}}
