# Generated by Django 5.2 on 2025-04-17 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverages', '0002_initial'),
        ('enrollmentrequests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='coverage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_request_coverage', to='coverages.coveragereference'),
        ),
    ]
