# Autogenerated by devscripts/update-version.py

__version__ = '2025.04.23.001659'

RELEASE_GIT_HEAD = '741fd809bc4d301c19b53877692ae510334a6750'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2025.04.23.001659dev'
