# Generated by Django 5.1.1 on 2024-10-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artd_siigo", "0002_rename_pricelist_siigopricelist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siigopricelist",
            name="json_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON data for the price list",
                null=True,
                verbose_name="JSON Data",
            ),
        ),
    ]
