# Generated by Django 5.1.1 on 2024-10-07 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "artd_siigo",
            "0020_alter_siigoproduct_prices_alter_siigoproduct_taxes_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siigoproduct",
            name="prices",
        ),
        migrations.AddField(
            model_name="siigoproductprice",
            name="product",
            field=models.ForeignKey(
                default="",
                help_text="Product for the price",
                on_delete=django.db.models.deletion.CASCADE,
                to="artd_siigo.siigoproduct",
                verbose_name="Product",
            ),
            preserve_default=False,
        ),
    ]
