# Generated by Django 5.1.1 on 2024-10-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artd_siigo", "0021_remove_siigoproduct_prices_siigoproductprice_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siigoproduct",
            name="taxes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Taxes for the product",
                to="artd_siigo.siigotax",
                verbose_name="Taxes",
            ),
        ),
    ]
