# Generated by Django 5.1.1 on 2025-03-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artd_siigo", "0058_siigocustomer_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siigocustomer",
            name="check_digit",
            field=models.CharField(
                blank=True,
                help_text="Check digit of the customer",
                max_length=10,
                null=True,
                verbose_name="Check Digit",
            ),
        ),
        migrations.AlterField(
            model_name="siigocustomer",
            name="commercial_name",
            field=models.CharField(
                blank=True,
                help_text="Commercial name of the customer",
                max_length=250,
                null=True,
                verbose_name="Commercial Name",
            ),
        ),
        migrations.AlterField(
            model_name="siigocustomer",
            name="identification",
            field=models.CharField(
                blank=True,
                help_text="Identification of the customer",
                max_length=25,
                null=True,
                verbose_name="Identification",
            ),
        ),
    ]
