# Generated by Django 5.1.1 on 2025-03-22 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artd_partner", "0010_partner_signed_key"),
        ("artd_siigo", "0064_siigoorderinvoice_json_data"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="billconfig",
            unique_together={("partner", "artd_document_type")},
        ),
    ]
