# Generated by Django 5.1.1 on 2025-03-24 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artd_order", "0009_order_created_by"),
        ("artd_partner", "0010_partner_signed_key"),
        ("artd_siigo", "0071_rename_siido_id_siigouser_siigo_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethodMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Status of the record",
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "order_payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artd_order.orderpaymentmethod",
                        verbose_name="Order Payment Method",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_method_mappings",
                        to="artd_partner.partner",
                        verbose_name="Partner",
                    ),
                ),
                (
                    "siigo_payment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artd_siigo.siigopaymenttype",
                        verbose_name="Siigo Payment Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapping Payment Method ",
                "verbose_name_plural": "Mapping Payment Methods",
            },
        ),
    ]
