# Generated by Django 5.2 on 2025-04-14 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentnotices', '0001_initial'),
        ('practitionerroles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentnoticepayeereference',
            name='practitioner_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_notice_payee_reference', to='practitionerroles.practitionerrole'),
        ),
        migrations.AlterField(
            model_name='paymentnoticereporterreference',
            name='practitioner_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_notice_reporter_reference', to='practitionerroles.practitionerrole'),
        ),
    ]
