from libuseful.exception import *
from libuseful.lib_logger import *
from .CPropTouch import CPropSheet as CPropSheet, CPropTouch as CPropTouch
from .ParsedEvts import ParsedEvts as ParsedEvts, RawEvts as RawEvts
from _typeshed import Incomplete
from touch_android.recorder.CTProperty import TouchType as TouchType

logger: Incomplete

class CParseTouch:
    class TouchMODE:
        SINGLE: str
        MULTI: str
    DEF_CLICK_DURATION: float
    DEF_CLICK_POSGAP: tuple
    @property
    def SD_posX(self): ...
    @property
    def SD_posY(self): ...
    def parse(self, src_path: str) -> CPropTouch: ...
    def __init__(self, mode: TouchMODE, click_duration: float = ..., click_posgap: tuple = ...) -> None: ...
    def __del__(self) -> None: ...

class CParse_Stouch(CParseTouch):
    def parse(self, src_path: str): ...
    def __init__(self, click_duration: float = ..., click_posgap: tuple = ...) -> None: ...
    def __del__(self) -> None: ...

class CParse_Mtouch(CParseTouch):
    def parse(self, src_path: str): ...
    def __init__(self, click_duration: float = ..., click_posgap: tuple = ...) -> None: ...
    def __del__(self) -> None: ...
