max_raw_data_days = 14
typical_tracked_events =['COMMISIONING','DATA_LOSS','DATA_LOSS_COP','EQUIPMENT_MALFUNCTION','HW_OUTAGE','HW_LOSS',
    'INSTALLATION_ERROR','PARTIAL_OCCUPANCY','POWER_OUTAGE','SETPOINT_ADJUSTMENT','SYSTEM_MAINTENANCE']