# Generated by Django 4.2.20 on 2025-04-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pupdater', '0003_alter_pipfreezesnapshot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipfreezesnapshot',
            options={'verbose_name_plural': 'Pip manager'},
        ),
        migrations.AlterModelOptions(
            name='requirementscheck',
            options={'verbose_name_plural': 'Requirements Check'},
        ),
    ]
