# Generated by Django 5.2 on 2025-04-14 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitionerroles', '0001_initial'),
        ('supplydelivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplydeliverydestinationreference',
            name='practitioner_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supply_delivery_destination_references_practitioner_role', to='practitionerroles.practitionerrole'),
        ),
        migrations.AlterField(
            model_name='supplydeliveryreceiverreference',
            name='practitioner_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supply_delivery_receiver_references_practitioner_role', to='practitionerroles.practitionerrole'),
        ),
        migrations.AlterField(
            model_name='supplydeliverysupplierreference',
            name='practitioner_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supply_delivery_supplier_references_practitioner_role', to='practitionerroles.practitionerrole'),
        ),
    ]
