sample_data_hugging_face = '''
{
	"activeFilters": {
		"pipeline_tag": [],
		"library": [],
		"dataset": [],
		"language": [],
		"license": [],
		"other": []
	},
	"models": [
		{
			"author": "deepseek-ai",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/6538815d1bdb3c40db94fbfa/xMBly9PUMphrFVMxLX4kq.png",
				"fullname": "DeepSeek",
				"name": "deepseek-ai",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 19061
			},
			"downloads": 285488,
			"gated": false,
			"id": "deepseek-ai/DeepSeek-R1",
			"inference": "custom-code",
			"lastModified": "2025-01-26T09:15:01.000Z",
			"likes": 4749,
			"pipeline_tag": "text-generation",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false,
			"widgetOutputUrls": ["foo"]
		},
		{
			"author": "deepseek-ai",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/6538815d1bdb3c40db94fbfa/xMBly9PUMphrFVMxLX4kq.png",
				"fullname": "DeepSeek",
				"name": "deepseek-ai",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 19061
			},
			"downloads": 51456,
			"gated": false,
			"id": "deepseek-ai/Janus-Pro-7B",
			"inference": "pipeline-library-pair-not-supported",
			"lastModified": "2025-01-27T16:12:12.000Z",
			"likes": 1832,
			"pipeline_tag": "any-to-any",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false
		},
		{
			"author": "deepseek-ai",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/6538815d1bdb3c40db94fbfa/xMBly9PUMphrFVMxLX4kq.png",
				"fullname": "DeepSeek",
				"name": "deepseek-ai",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 19061
			},
			"downloads": 373636,
			"gated": false,
			"id": "deepseek-ai/DeepSeek-V3",
			"inference": "custom-code",
			"lastModified": "2025-01-24T11:33:51.000Z",
			"likes": 2732,
			"pipeline_tag": "text-generation",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false,
			"widgetOutputUrls": ["foo1"]
		},
		{
			"author": "tencent",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/5dd96eb166059660ed1ee413/Lp3m-XLpjQGwBItlvn69q.png",
				"fullname": "Tencent",
				"name": "tencent",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 1741
			},
			"downloads": 20878,
			"gated": false,
			"id": "tencent/Hunyuan3D-2",
			"inference": "pipeline-library-pair-not-supported",
			"lastModified": "2025-01-24T06:01:29.000Z",
			"likes": 594,
			"pipeline_tag": "image-to-3d",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false
		},
		{
			"author": "deepseek-ai",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/6538815d1bdb3c40db94fbfa/xMBly9PUMphrFVMxLX4kq.png",
				"fullname": "DeepSeek",
				"name": "deepseek-ai",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 19061
			},
			"downloads": 164729,
			"gated": false,
			"id": "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
			"inference": "warm",
			"lastModified": "2025-01-26T09:15:32.000Z",
			"likes": 696,
			"pipeline_tag": "text-generation",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false,
			"widgetOutputUrls": ["foo2"]
		},
		{
			"author": "hexgrad",
			"authorData": {
				"_id": "6629552c96f529a39bac7c89",
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/6629552c96f529a39bac7c89/AJJtp6lphF1Ij8I2p9XFG.png",
				"fullname": "Hexgrad",
				"name": "hexgrad",
				"type": "user",
				"isPro": true,
				"isHf": false,
				"isMod": false,
				"followerCount": 525
			},
			"downloads": 46587,
			"gated": false,
			"id": "hexgrad/Kokoro-82M",
			"inference": "library-not-detected",
			"lastModified": "2025-01-29T00:57:14.000Z",
			"likes": 2538,
			"pipeline_tag": "text-to-speech",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false,
			"widgetOutputUrls": ["foo2"]
		},
		{
			"author": "HKUSTAudio",
			"authorData": {
				"avatarUrl": "https://www.gravatar.com/avatar/1337f563cc1d77d43225f022c8ed5b66?d=retro&size=100",
				"fullname": "HKUST Audio",
				"name": "HKUSTAudio",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 119
			},
			"downloads": 3832,
			"gated": "auto",
			"id": "HKUSTAudio/Llasa-3B",
			"inference": "library-not-detected",
			"lastModified": "2025-01-26T16:41:06.000Z",
			"likes": 374,
			"pipeline_tag": "text-to-speech",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false
		},
		{
			"author": "deepseek-ai",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/6538815d1bdb3c40db94fbfa/xMBly9PUMphrFVMxLX4kq.png",
				"fullname": "DeepSeek",
				"name": "deepseek-ai",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 19061
			},
			"downloads": 182424,
			"gated": false,
			"id": "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B",
			"inference": "warm",
			"lastModified": "2025-01-26T09:15:27.000Z",
			"likes": 534,
			"pipeline_tag": "text-generation",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false,
			"widgetOutputUrls": []
		},
		{
			"author": "deepseek-ai",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/6538815d1bdb3c40db94fbfa/xMBly9PUMphrFVMxLX4kq.png",
				"fullname": "DeepSeek",
				"name": "deepseek-ai",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 19061
			},
			"downloads": 15289,
			"gated": false,
			"id": "deepseek-ai/DeepSeek-R1-Zero",
			"inference": "custom-code",
			"lastModified": "2025-01-26T09:15:39.000Z",
			"likes": 598,
			"pipeline_tag": "text-generation",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false,
			"widgetOutputUrls": []
		},
		{
			"author": "deepseek-ai",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/6538815d1bdb3c40db94fbfa/xMBly9PUMphrFVMxLX4kq.png",
				"fullname": "DeepSeek",
				"name": "deepseek-ai",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 19061
			},
			"downloads": 10919,
			"gated": false,
			"id": "deepseek-ai/Janus-Pro-1B",
			"inference": "pipeline-library-pair-not-supported",
			"lastModified": "2025-01-27T16:12:30.000Z",
			"likes": 259,
			"pipeline_tag": "any-to-any",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false
		},
		{
			"author": "unsloth",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/62ecdc18b72a69615d6bd857/E4lkPz1TZNLzIFr_dR273.png",
				"fullname": "Unsloth AI",
				"name": "unsloth",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": true,
				"followerCount": 1747
			},
			"downloads": 142908,
			"gated": false,
			"id": "unsloth/DeepSeek-R1-GGUF",
			"inference": "custom-code",
			"lastModified": "2025-01-29T07:56:53.000Z",
			"likes": 286,
			"pipeline_tag": "text-generation",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false,
			"widgetOutputUrls": []
		},
		{
			"author": "m-a-p",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/63839e9962badff4326cf360/k4Q7R4XLDMp_1VF4C6GEd.jpeg",
				"fullname": "Multimodal Art Projection",
				"name": "m-a-p",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 434
			},
			"downloads": 2503,
			"gated": false,
			"id": "m-a-p/YuE-s1-7B-anneal-en-cot",
			"inference": "library-not-detected",
			"lastModified": "2025-01-28T15:48:42.000Z",
			"likes": 202,
			"pipeline_tag": "text-generation",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false,
			"widgetOutputUrls": []
		},
		{
			"author": "deepseek-ai",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/6538815d1bdb3c40db94fbfa/xMBly9PUMphrFVMxLX4kq.png",
				"fullname": "DeepSeek",
				"name": "deepseek-ai",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 19061
			},
			"downloads": 70300,
			"gated": false,
			"id": "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
			"inference": "cold",
			"lastModified": "2025-01-26T09:15:21.000Z",
			"likes": 356,
			"pipeline_tag": "text-generation",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false,
			"widgetOutputUrls": []
		},
		{
			"author": "deepseek-ai",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/6538815d1bdb3c40db94fbfa/xMBly9PUMphrFVMxLX4kq.png",
				"fullname": "DeepSeek",
				"name": "deepseek-ai",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 19061
			},
			"downloads": 92622,
			"gated": false,
			"id": "deepseek-ai/DeepSeek-R1-Distill-Llama-8B",
			"inference": "cold",
			"lastModified": "2025-01-26T09:15:24.000Z",
			"likes": 320,
			"pipeline_tag": "text-generation",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false,
			"widgetOutputUrls": []
		},
		{
			"author": "cyberagent",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/1656557093040-62b397ef2d2f388f4451883d.png",
				"fullname": "CyberAgent",
				"name": "cyberagent",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 410
			},
			"downloads": 3450,
			"gated": false,
			"id": "cyberagent/DeepSeek-R1-Distill-Qwen-32B-Japanese",
			"inference": "explicit-opt-out",
			"lastModified": "2025-01-27T07:08:49.000Z",
			"likes": 174,
			"pipeline_tag": "text-generation",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false
		},
		{
			"author": "Qwen",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/620760a26e3b7210c2ff1943/-s1gyJfvbE1RgO5iBeNOi.png",
				"fullname": "Qwen",
				"name": "Qwen",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 11582
			},
			"downloads": 2977,
			"gated": false,
			"id": "Qwen/Qwen2.5-14B-Instruct-1M",
			"inference": "cold",
			"lastModified": "2025-01-29T12:38:27.000Z",
			"likes": 162,
			"pipeline_tag": "text-generation",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false,
			"widgetOutputUrls": []
		},
		{
			"author": "Qwen",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/620760a26e3b7210c2ff1943/-s1gyJfvbE1RgO5iBeNOi.png",
				"fullname": "Qwen",
				"name": "Qwen",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 11582
			},
			"downloads": 18366,
			"gated": false,
			"id": "Qwen/Qwen2.5-VL-7B-Instruct",
			"inference": "loading",
			"lastModified": "2025-01-27T18:41:00.000Z",
			"likes": 158,
			"pipeline_tag": "image-text-to-text",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false,
			"widgetOutputUrls": []
		},
		{
			"author": "black-forest-labs",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/62cfefa74b3e8dc1e32e38bf/GgkglHn3sIo6C5XGTtZSs.png",
				"fullname": "Black Forest Labs",
				"name": "black-forest-labs",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 8868
			},
			"downloads": 1548084,
			"gated": "auto",
			"id": "black-forest-labs/FLUX.1-dev",
			"inference": "warm",
			"lastModified": "2024-08-16T14:38:19.000Z",
			"likes": 8321,
			"pipeline_tag": "text-to-image",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false
		},
		{
			"author": "deepseek-ai",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/6538815d1bdb3c40db94fbfa/xMBly9PUMphrFVMxLX4kq.png",
				"fullname": "DeepSeek",
				"name": "deepseek-ai",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 19061
			},
			"downloads": 23524,
			"gated": false,
			"id": "deepseek-ai/DeepSeek-V3-Base",
			"inference": "library-not-detected",
			"lastModified": "2025-01-24T06:58:55.000Z",
			"likes": 1444,
			"private": false,
			"repoType": "model",
			"isLikedByUser": false
		},
		{
			"author": "Qwen",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/620760a26e3b7210c2ff1943/-s1gyJfvbE1RgO5iBeNOi.png",
				"fullname": "Qwen",
				"name": "Qwen",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 11582
			},
			"downloads": 2847,
			"gated": false,
			"id": "Qwen/Qwen2.5-VL-72B-Instruct",
			"inference": "pipeline-library-pair-not-supported",
			"lastModified": "2025-01-27T18:44:06.000Z",
			"likes": 143,
			"pipeline_tag": "image-text-to-text",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false,
			"widgetOutputUrls": []
		},
		{
			"author": "Qwen",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/620760a26e3b7210c2ff1943/-s1gyJfvbE1RgO5iBeNOi.png",
				"fullname": "Qwen",
				"name": "Qwen",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 11582
			},
			"downloads": 6914,
			"gated": false,
			"id": "Qwen/Qwen2.5-7B-Instruct-1M",
			"inference": "cold",
			"lastModified": "2025-01-29T12:39:09.000Z",
			"likes": 133,
			"pipeline_tag": "text-generation",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false,
			"widgetOutputUrls": []
		},
		{
			"author": "openbmb",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/1670387859384-633fe7784b362488336bbfad.png",
				"fullname": "OpenBMB",
				"name": "openbmb",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 811
			},
			"downloads": 135782,
			"gated": false,
			"id": "openbmb/MiniCPM-o-2_6",
			"inference": "custom-code",
			"lastModified": "2025-01-26T16:02:13.000Z",
			"likes": 867,
			"pipeline_tag": "any-to-any",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false
		},
		{
			"author": "deepseek-ai",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/6538815d1bdb3c40db94fbfa/xMBly9PUMphrFVMxLX4kq.png",
				"fullname": "DeepSeek",
				"name": "deepseek-ai",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 19061
			},
			"downloads": 119679,
			"gated": false,
			"id": "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
			"inference": "cold",
			"lastModified": "2025-01-26T09:15:35.000Z",
			"likes": 259,
			"pipeline_tag": "text-generation",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false,
			"widgetOutputUrls": []
		},
		{
			"author": "deepseek-ai",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/6538815d1bdb3c40db94fbfa/xMBly9PUMphrFVMxLX4kq.png",
				"fullname": "DeepSeek",
				"name": "deepseek-ai",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 19061
			},
			"downloads": 58308,
			"gated": false,
			"id": "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
			"inference": "cold",
			"lastModified": "2025-01-26T09:15:29.000Z",
			"likes": 248,
			"pipeline_tag": "text-generation",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false,
			"widgetOutputUrls": []
		},
		{
			"author": "microsoft",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/1583646260758-5e64858c87403103f9f1055d.png",
				"fullname": "Microsoft",
				"name": "microsoft",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 7844
			},
			"downloads": 264891,
			"gated": false,
			"id": "microsoft/phi-4",
			"inference": "cold",
			"lastModified": "2025-01-08T20:55:58.000Z",
			"likes": 1611,
			"pipeline_tag": "text-generation",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false,
			"widgetOutputUrls": []
		},
		{
			"author": "ostris",
			"authorData": {
				"_id": "643cb43e6eeb746f5ad81c26",
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/643cb43e6eeb746f5ad81c26/_DUtzHpNtpTeDw7u0oYyX.png",
				"fullname": "Jaret Burkett",
				"name": "ostris",
				"type": "user",
				"isPro": false,
				"isHf": false,
				"isMod": false,
				"followerCount": 354
			},
			"downloads": 14388,
			"gated": false,
			"id": "ostris/Flex.1-alpha",
			"inference": "loading",
			"lastModified": "2025-01-19T03:23:32.000Z",
			"likes": 312,
			"pipeline_tag": "text-to-image",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false
		},
		{
			"author": "bytedance-research",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/6535c9e88bde2fae19b6fb25/7a1zq0juEwFJVCIShnLI-.png",
				"fullname": "bytedance-research",
				"name": "bytedance-research",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 200
			},
			"downloads": 2330,
			"gated": false,
			"id": "bytedance-research/UI-TARS-7B-SFT",
			"inference": "pipeline-library-pair-not-supported",
			"lastModified": "2025-01-25T15:05:42.000Z",
			"likes": 124,
			"pipeline_tag": "image-text-to-text",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false,
			"widgetOutputUrls": []
		},
		{
			"author": "HuggingFaceTB",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/651e96991b97c9f33d26bde6/e4VK7uW5sTeCYupD0s_ob.png",
				"fullname": "Hugging Face TB Research",
				"name": "HuggingFaceTB",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": true,
				"followerCount": 963
			},
			"downloads": 9411,
			"gated": false,
			"id": "HuggingFaceTB/SmolVLM-256M-Instruct",
			"inference": "pipeline-library-pair-not-supported",
			"lastModified": "2025-01-23T12:53:31.000Z",
			"likes": 99,
			"pipeline_tag": "image-text-to-text",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false,
			"widgetOutputUrls": []
		},
		{
			"author": "jinaai",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/603763514de52ff951d89793/AFoybzd5lpBQXEBrQHuTt.png",
				"fullname": "Jina AI",
				"name": "jinaai",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": true,
				"followerCount": 651
			},
			"downloads": 20986,
			"gated": false,
			"id": "jinaai/ReaderLM-v2",
			"inference": "explicit-opt-out",
			"lastModified": "2025-01-22T03:44:56.000Z",
			"likes": 445,
			"pipeline_tag": "text-generation",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false
		},
		{
			"author": "bytedance-research",
			"authorData": {
				"avatarUrl": "https://cdn-avatars.huggingface.co/v1/production/uploads/6535c9e88bde2fae19b6fb25/7a1zq0juEwFJVCIShnLI-.png",
				"fullname": "bytedance-research",
				"name": "bytedance-research",
				"type": "org",
				"isHf": false,
				"isMod": false,
				"isEnterprise": false,
				"followerCount": 200
			},
			"downloads": 14005,
			"gated": false,
			"id": "bytedance-research/UI-TARS-7B-DPO",
			"inference": "pipeline-library-pair-not-supported",
			"lastModified": "2025-01-25T15:05:08.000Z",
			"likes": 97,
			"pipeline_tag": "image-text-to-text",
			"private": false,
			"repoType": "model",
			"isLikedByUser": false,
			"widgetOutputUrls": []
		}
	],
	"numItemsPerPage": 30,
	"numTotalItems": 1348708,
	"pageIndex": 0
}
'''