"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2022 The ChromiumOS Authors
Use of this source code is governed by a BSD-style license that can be
found in the LICENSE file.
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SwipeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X0_FIELD_NUMBER: builtins.int
    Y0_FIELD_NUMBER: builtins.int
    X1_FIELD_NUMBER: builtins.int
    Y1_FIELD_NUMBER: builtins.int
    DX_FIELD_NUMBER: builtins.int
    DY_FIELD_NUMBER: builtins.int
    TOUCHES_FIELD_NUMBER: builtins.int
    TIME_MILLI_SECONDS_FIELD_NUMBER: builtins.int
    x0: builtins.int
    """x0 represents the x coordinate of the starting point of the swipe."""
    y0: builtins.int
    """y0 represents the y coordinate of the starting point of the swipe."""
    x1: builtins.int
    """x1 represents the x coordinate of the end point of the swipe."""
    y1: builtins.int
    """y1 represents the y coordinate of the end point of the swipe."""
    dx: builtins.int
    """dx represents the x coordinate of the offset between touches.
    Touches are separated by (dx, dy). For example, in a 3-touch swipe, the
    touches begin at (x0, y0), (x0+dx, y0+dy), (x0+2dx, y0+2dy).
    """
    dy: builtins.int
    """dy represents the y coordinate of the offset between touches.
    Touches are separated by (dx, dy). For example, in a 3-touch swipe, the
    touches begin at (x0, y0), (x0+dx, y0+dy), (x0+2dx, y0+2dy).
    """
    touches: builtins.int
    """Touches represents the number of touches and has to be larger than 0."""
    time_milli_seconds: builtins.int
    """TimeMilliSeconds represents how long the swipe should last. If
    TimeMilliSeconds is less than 5 milliseconds, 5 milliseconds will be used
    instead.
    """
    def __init__(
        self,
        *,
        x0: builtins.int = ...,
        y0: builtins.int = ...,
        x1: builtins.int = ...,
        y1: builtins.int = ...,
        dx: builtins.int = ...,
        dy: builtins.int = ...,
        touches: builtins.int = ...,
        time_milli_seconds: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["dx", b"dx", "dy", b"dy", "time_milli_seconds", b"time_milli_seconds", "touches", b"touches", "x0", b"x0", "x1", b"x1", "y0", b"y0", "y1", b"y1"]) -> None: ...

global___SwipeRequest = SwipeRequest
