# Generated by Django 5.2 on 2025-04-14 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimresponses', '0004_initial'),
        ('paymentreconciliations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreconciliationallocation',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_reconciliation_allocation_response', to='claimresponses.claimresponse'),
        ),
    ]
