# Generated by Django 5.2 on 2025-04-14 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentreconciliations', '0002_paymentreconciliationallocation_response'),
        ('practitionerroles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreconciliationallocation',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_reconciliation_allocation_responsible', to='practitionerroles.practitionerrolereference'),
        ),
    ]
