# Generated by Django 5.2 on 2025-04-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodeofcare', '0003_initial'),
        ('servicerequests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodeofcare',
            name='referral_request',
            field=models.ManyToManyField(blank=True, related_name='episode_of_care_referral_request', to='servicerequests.servicerequestreference'),
        ),
    ]
