# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tast/cros/services/cros/ui/check_virtual_keyboard_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tast/cros/services/cros/ui/check_virtual_keyboard_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?tast/cros/services/cros/ui/check_virtual_keyboard_service.proto\x12\x0ctast.cros.ui\x1a\x1bgoogle/protobuf/empty.proto\"z\n\x11NewBrowserRequest\x12\x41\n\x0c\x62rowser_type\x18\x01 \x01(\x0e\x32+.tast.cros.ui.NewBrowserRequest.BrowserType\"\"\n\x0b\x42rowserType\x12\x07\n\x03\x41SH\x10\x00\x12\n\n\x06LACROS\x10\x01\"9\n\x1b\x43heckVirtualKeyboardRequest\x12\x1a\n\x12is_dut_tablet_mode\x18\x01 \x01(\x08\"C\n\x1c\x43heckVirtualKeyboardResponse\x12#\n\x1bis_virtual_keyboard_present\x18\x01 \x01(\x08\x32\xa5\x05\n\x1b\x43heckVirtualKeyboardService\x12N\n\x11NewChromeLoggedIn\x12\x1f.tast.cros.ui.NewBrowserRequest\x1a\x16.google.protobuf.Empty\"\x00\x12?\n\x0b\x43loseChrome\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12\x42\n\x0eOpenChromePage\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12I\n\x15\x43lickChromeAddressBar\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12I\n\x15TouchChromeAddressBar\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12x\n\x1d\x43heckVirtualKeyboardIsPresent\x12).tast.cros.ui.CheckVirtualKeyboardRequest\x1a*.tast.cros.ui.CheckVirtualKeyboardResponse\"\x00\x12U\n\x0e\x43lickSearchBar\x12).tast.cros.ui.CheckVirtualKeyboardRequest\x1a\x16.google.protobuf.Empty\"\x00\x12J\n\x16\x45nableOnscreenKeyboard\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x42\x32Z0go.chromium.org/tast-tests/cros/services/cros/uib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tast.cros.services.cros.ui.check_virtual_keyboard_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0go.chromium.org/tast-tests/cros/services/cros/ui'
  _globals['_NEWBROWSERREQUEST']._serialized_start=110
  _globals['_NEWBROWSERREQUEST']._serialized_end=232
  _globals['_NEWBROWSERREQUEST_BROWSERTYPE']._serialized_start=198
  _globals['_NEWBROWSERREQUEST_BROWSERTYPE']._serialized_end=232
  _globals['_CHECKVIRTUALKEYBOARDREQUEST']._serialized_start=234
  _globals['_CHECKVIRTUALKEYBOARDREQUEST']._serialized_end=291
  _globals['_CHECKVIRTUALKEYBOARDRESPONSE']._serialized_start=293
  _globals['_CHECKVIRTUALKEYBOARDRESPONSE']._serialized_end=360
  _globals['_CHECKVIRTUALKEYBOARDSERVICE']._serialized_start=363
  _globals['_CHECKVIRTUALKEYBOARDSERVICE']._serialized_end=1040
# @@protoc_insertion_point(module_scope)
