key = """-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIC9DdNV8BGa6EnE/d0KlDi3G7NakwRWfaT2N/L6puzkxoAoGCCqGSM49
AwEHoUQDQgAE50PBSUwaRpcPuECIYhmw0c9OPCfcv5rZFWWuPhoTADKlqzn6zn1I
tlo/wyVOOnPopjNttWYj+0eM3eH0gFVQQQ==
-----END EC PRIVATE KEY-----
"""

cert = """-----BEGIN CERTIFICATE-----
MIIB6DCCAY8CFCpuNDKg7fu0eZS+Iu5580GuMNSvMAoGCCqGSM49BAMCMHcxCzAJ
BgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0eTEVMBMGA1UE
CgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25hbCBVbml0MRQw
EgYDVQQDDAtDb21tb24gTmFtZTAeFw0yNTA0MjEwMjU4MjVaFw0zNTA0MTkwMjU4
MjVaMHcxCzAJBgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0
eTEVMBMGA1UECgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25h
bCBVbml0MRQwEgYDVQQDDAtDb21tb24gTmFtZTBZMBMGByqGSM49AgEGCCqGSM49
AwEHA0IABOdDwUlMGkaXD7hAiGIZsNHPTjwn3L+a2RVlrj4aEwAypas5+s59SLZa
P8MlTjpz6KYzbbVmI/tHjN3h9IBVUEEwCgYIKoZIzj0EAwIDRwAwRAIgG/4f7tOw
nkGd6a9OdRuiUcoj6y6rsVqpC+HZ8Pjaa7ECIFDEvy1uwHvUIiwX9myHLPThyZV7
g8klshc/jispYjDg
-----END CERTIFICATE-----
"""