# Generated by Django 5.2 on 2025-04-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
        ('healthcareservices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareservice',
            name='endpoint',
            field=models.ManyToManyField(blank=True, related_name='healthcareservice_endpoint', to='endpoints.endpoint'),
        ),
    ]
