# Generated by Django 5.1.1 on 2024-10-06 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artd_partner", "0007_position_partner"),
        ("artd_siigo", "0005_rename_warehouse_siigowarehouse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiigoUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Status of the record",
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Username of the user",
                        max_length=250,
                        verbose_name="Username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="First name of the user",
                        max_length=250,
                        verbose_name="First Name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Last name of the user",
                        max_length=250,
                        verbose_name="Last Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email of the user",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Active status of the user",
                        verbose_name="Active",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        help_text="Partner associated with the user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artd_partner.partner",
                        verbose_name="Partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Siigo User",
                "verbose_name_plural": "Siigo Users",
            },
        ),
    ]
