# Generated by Django 5.1.1 on 2024-10-06 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artd_siigo", "0009_siigodocumenttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="siigodocumenttype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 10, 6, 21, 52, 47, 607286, tzinfo=datetime.timezone.utc
                ),
                help_text="Date and time when the record was created",
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="siigodocumenttype",
            name="status",
            field=models.BooleanField(
                default=True, help_text="Status of the record", verbose_name="Status"
            ),
        ),
        migrations.AddField(
            model_name="siigodocumenttype",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when the record was updated",
                verbose_name="Updated at",
            ),
        ),
    ]
