# Generated by Django 5.1.1 on 2024-10-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artd_siigo", "0011_alter_siigodocumenttype_options_siigopaymenttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="siigopaymenttype",
            name="siigo_id",
            field=models.CharField(
                default="",
                help_text="Siigo ID for the payment type",
                max_length=250,
                verbose_name="Siigo ID",
            ),
            preserve_default=False,
        ),
    ]
