# Generated by Django 5.1.1 on 2024-10-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artd_siigo", "0018_alter_siigoproduct_prices_alter_siigoproduct_taxes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siigoproduct",
            name="warehouse",
        ),
        migrations.AddField(
            model_name="siigoproduct",
            name="warehouses",
            field=models.ManyToManyField(
                blank=True,
                help_text="Warehouses for the product",
                to="artd_siigo.siigowarehouse",
                verbose_name="Warehouses",
            ),
        ),
    ]
