# Generated by Django 5.1.1 on 2024-10-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artd_siigo", "0030_fiscalresponsibilitiesmapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiscalresponsibilitiesmapping",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Code",
                max_length=100,
                null=True,
                verbose_name="Code",
            ),
        ),
    ]
