# Generated by Django 5.1.1 on 2024-10-28 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artd_siigo", "0041_siigoproductproxy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siigoproductproxy",
            options={
                "verbose_name": "Siigo Product Account Group",
                "verbose_name_plural": "Siigo Product Account Groups",
            },
        ),
    ]
