# Generated by Django 5.1.1 on 2024-10-29 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artd_siigo", "0044_billconfig_generate_electronic_bill_usermapping"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billconfig",
            old_name="generate_electronic_bill",
            new_name="generate_electronic_document",
        ),
    ]
