# Generated by Django 5.1.1 on 2024-10-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "artd_siigo",
            "0045_rename_generate_electronic_bill_billconfig_generate_electronic_document",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="billconfig",
            name="generate_electronic_document",
            field=models.BooleanField(
                default=False, verbose_name="Generate Electronic Document"
            ),
        ),
    ]
