# Generated by Django 5.1.1 on 2025-03-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artd_siigo", "0055_siigocustomer_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="siigocustomer",
            name="synced",
            field=models.BooleanField(
                default=False,
                help_text="Synced status of the customer",
                verbose_name="Synced",
            ),
        ),
    ]
