# Generated by Django 5.1.1 on 2025-03-21 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artd_product", "0017_remove_tax_partner_brand_partner"),
        ("artd_siigo", "0059_alter_siigocustomer_check_digit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siigoproduct",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="artd_product.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="siigoproduct",
            name="source",
            field=models.CharField(
                default="SIIGO",
                help_text="Source of the customer",
                max_length=250,
                verbose_name="Source",
            ),
        ),
        migrations.AddField(
            model_name="siigoproduct",
            name="synchronized",
            field=models.BooleanField(
                default=False,
                help_text="Synced status of the customer",
                verbose_name="Synced",
            ),
        ),
    ]
