# Generated by Django 5.2 on 2025-04-14 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitionerroles', '0001_initial'),
        ('servicerequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequestperformerreference',
            name='practitioner_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request_performer_practitioner_role', to='practitionerroles.practitionerrole'),
        ),
        migrations.AlterField(
            model_name='servicerequestrequesterreference',
            name='practitioner_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request_requester_practitioner_role', to='practitionerroles.practitionerrole'),
        ),
    ]
