# Generated by Django 5.0.7 on 2025-04-18 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentor_video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoprocessingrequest',
            options={'verbose_name': 'Video Processing Request', 'verbose_name_plural': '1- Video Processing Requests'},
        ),
    ]
