
"""
    Access Control API

    One Ring to rule them all, One ring to find them; One ring to integrate them all and in a short time, generate a lot of money 🤑.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bsport_access_control_client.models.patched_place_restriction import PatchedPlaceRestriction


class TestPatchedPlaceRestriction(unittest.TestCase):
    """PatchedPlaceRestriction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchedPlaceRestriction:
        """Test PatchedPlaceRestriction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchedPlaceRestriction`
        """
        model = PatchedPlaceRestriction()
        if include_optional:
            return PatchedPlaceRestriction(
                id = 56,
                start_datetime = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_datetime = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                from_time = '',
                to_time = '',
                monday = True,
                tuesday = True,
                wednesday = True,
                thursday = True,
                friday = True,
                saturday = True,
                sunday = True,
                purpose_id = '',
                purpose_name = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                place = 56,
                provider_config = ''
            )
        else:
            return PatchedPlaceRestriction(
        )
        """

    def testPatchedPlaceRestriction(self):
        """Test PatchedPlaceRestriction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
