
"""
    Access Control API

    One Ring to rule them all, One ring to find them; One ring to integrate them all and in a short time, generate a lot of money 🤑.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bsport_access_control_client.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_auth_token_create(self) -> None:
        """Test case for auth_token_create

        """
        pass

    def test_auth_token_refresh_create(self) -> None:
        """Test case for auth_token_refresh_create

        """
        pass

    def test_auth_token_verify_create(self) -> None:
        """Test case for auth_token_verify_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
