"""
Access Control API

One Ring to rule them all, One ring to find them; One ring to integrate them all and in a short time, generate a lot of money 🤑.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from bsport_access_control_client.models.paginated_provider_config_list import (
    PaginatedProviderConfigList,
)


class TestPaginatedProviderConfigList(unittest.TestCase):
    """PaginatedProviderConfigList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedProviderConfigList:
        """Test PaginatedProviderConfigList
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PaginatedProviderConfigList`
        """
        model = PaginatedProviderConfigList()
        if include_optional:
            return PaginatedProviderConfigList(
                count = 123,
                next = 'http://api.example.org/accounts/?page=4',
                previous = 'http://api.example.org/accounts/?page=2',
                results = [
                    bsport_access_control_client.models.provider_config.ProviderConfig(
                        id = '', 
                        api_key = '', 
                        provider_type = null, 
                        timezone = '', 
                        user = 56, )
                    ]
            )
        else:
            return PaginatedProviderConfigList(
                count = 123,
                results = [
                    bsport_access_control_client.models.provider_config.ProviderConfig(
                        id = '', 
                        api_key = '', 
                        provider_type = null, 
                        timezone = '', 
                        user = 56, )
                    ],
        )
        """

    def testPaginatedProviderConfigList(self):
        """Test PaginatedProviderConfigList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
