# coding: utf-8

"""
    Sureel API

    API for the Sureel network.

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_own_collections200_response_user_role import GetOwnCollections200ResponseUserRole

class TestGetOwnCollections200ResponseUserRole(unittest.TestCase):
    """GetOwnCollections200ResponseUserRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOwnCollections200ResponseUserRole:
        """Test GetOwnCollections200ResponseUserRole
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOwnCollections200ResponseUserRole`
        """
        model = GetOwnCollections200ResponseUserRole()
        if include_optional:
            return GetOwnCollections200ResponseUserRole(
            )
        else:
            return GetOwnCollections200ResponseUserRole(
        )
        """

    def testGetOwnCollections200ResponseUserRole(self):
        """Test GetOwnCollections200ResponseUserRole"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
