# Generated by Django 5.1.5 on 2025-04-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(help_text='Google Ads campaign ID', max_length=255, unique=True)),
                ('customer_id', models.CharField(blank=True, help_text='Google Ads customer ID', max_length=255, null=True)),
                ('campaign_name', models.CharField(blank=True, help_text='Campaign name', max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(2, 'Enabled'), (3, 'Paused'), (4, 'Removed')], help_text='Campaign status')),
            ],
            options={
                'verbose_name': 'Campaign Status',
                'verbose_name_plural': 'Campaign Statuses',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Google Ads API OAuth refresh token', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the token was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the token was last updated')),
            ],
            options={
                'verbose_name': 'Google Ads Token',
                'verbose_name_plural': 'Google Ads Tokens',
            },
        ),
    ]
