
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-21T19:02:18+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "906f2ff8e0155126f116dad11578e63816e9152e",
 "version": "1.5.0.post2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
