# Generated by Django 5.2 on 2025-04-10 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventoryreports', '0001_initial'),
        ('patients', '0001_initial'),
        ('practitioners', '0001_initial'),
        ('relatedpersons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreportreporterreference',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_report_reporter_reference_patient', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='inventoryreportreporterreference',
            name='practitioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_report_reporter_reference_practitioner', to='practitioners.practitioner'),
        ),
        migrations.AddField(
            model_name='inventoryreportreporterreference',
            name='related_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_report_reporter_reference_related_person', to='relatedpersons.relatedperson'),
        ),
        migrations.AddField(
            model_name='inventoryreport',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_report', to='inventoryreports.inventoryreportreporterreference'),
        ),
    ]
