HEROES = [
        "Ogre Magi", "Alchemist", "Axe", "Bristleback", "Centaur Warrunner",
        "Chaos Knight", "Dawnbreaker", "Doom", "Dragon Knight", "Earth Spirit",
        "Earthshaker", "Elder Titan", "Huskar", "Kunkka", "Legion Commander",
        "Lifestealer", "Mars", "Night Stalker", "Omniknight", "Primal Beast",
        "Pudge", "Slardar", "Spirit Breaker", "Sven", "Tidehunter", "Tiny",
        "Treant Protector", "Tusk", "Underlord", "Undying", "Wraith King",
        "Anti-Mage", "Arc Warden", "Bloodseeker", "Bounty Hunter", "Clinkz",
        "Drow Ranger", "Ember Spirit", "Faceless Void", "Gyrocopter", "Hoodwink",
        "Juggernaut", "Kez", "Luna", "Medusa", "Meepo", "Monkey King",
        "Morphling", "Naga Siren", "Phantom Assassin", "Phantom Lancer", "Razor",
        "Riki", "Shadow Fiend", "Slark", "Sniper", "Spectre", "Templar Assassin",
        "Terrorblade", "Troll Warlord", "Ursa", "Viper", "Weaver",
        "Ancient Apparition", "Crystal Maiden", "Death Prophet", "Disruptor",
        "Enchantress", "Grimstroke", "Invoker", "Jakiro", "Keeper of the Light",
        "Leshrac", "Lich", "Lina", "Lion", "Muerta", "Nature's Prophet",
        "Necrophos", "Oracle", "Outworld Devourer", "Puck", "Pugna", "Queen of Pain",
        "Ringmaster", "Rubick", "Shadow Demon", "Shadow Shaman", "Silencer",
        "Skywrath Mage", "Storm Spirit", "Tinker", "Warlock", "Witch Doctor", "Zeus",
        "Abaddon", "Bane", "Batrider", "Chen", "Beastmaster", "Brewmaster",
        "Broodmother", "Clockwerk", "Dark Seer", "Dark Willow", "Dazzle", "Enigma",
        "Io", "Lone Druid", "Lycan", "Magnus", "Marci", "Mirana", "Nyx Assassin",
        "Pangolier", "Phoenix", "Sand King", "Snapfire", "Techies", "Timbersaw",
        "Vengeful Spirit", "Venomancer", "Visage", "Void Spirit", "Windranger",
        "Winter Wyvern"
    ]