from setuptools import setup, find_packages

setup(
    name='fx-shared-models',
    version='0.2.28',
    packages=find_packages(),
    package_dir={'': '.'},
    install_requires=[
        'Django>=3.0',
        'django-environ>=0.10.0',
    ],
    python_requires='>=3.8',
    author='FX Backend',
    author_email='fxbackend@gmail.com',
    description='Shared models for FX Backend',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/fxbackend/fx-shared-models',
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.8',
        'Framework :: Django',
    ],
    include_package_data=True,
    package_data={
        'shared_models': [
            'accounts/*',
            'common/*',
            'company_ba/*',
            'crypto_wallet/*', 
            'customer_crypto_wallet/*',
            'customer_upi/*',
            'customers/*',
            'email_log/*',
            'ib_commission/*',
            'referrals/*',
            'services/*',
            'system_settings/*',
            'transactions/*',
            'ui_elements/*',
            'upi_id/*',
            'users/*',
        ],
    },
) 