# coding: utf-8

"""
    Sureel API

    API for the Sureel network.

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.artist_collections_inner_synthesis_rules import ArtistCollectionsInnerSynthesisRules

class TestArtistCollectionsInnerSynthesisRules(unittest.TestCase):
    """ArtistCollectionsInnerSynthesisRules unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ArtistCollectionsInnerSynthesisRules:
        """Test ArtistCollectionsInnerSynthesisRules
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ArtistCollectionsInnerSynthesisRules`
        """
        model = ArtistCollectionsInnerSynthesisRules()
        if include_optional:
            return ArtistCollectionsInnerSynthesisRules(
                no_attribution_greater_than = 1.337,
                no_attribution_smaller_than = 1.337,
                no_shared_attribution_with_artist = '',
                no_shared_attribution_with_genre = ''
            )
        else:
            return ArtistCollectionsInnerSynthesisRules(
        )
        """

    def testArtistCollectionsInnerSynthesisRules(self):
        """Test ArtistCollectionsInnerSynthesisRules"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
