from enum import Enum

class RabbitMQRoutingKey(str, Enum):
    AUTH_OTP = 'AUTH_OTP'
    AUTH_LOGIN = 'AUTH_LOGIN'
    AUTH_DATA = 'AUTH_DATA'
    POSTS_CREATE = 'POSTS_CREATE'
    POSTS_LIST = 'POSTS_LIST'
    POSTS_DELETE = 'POSTS_DELETE'
    POSTS_UPDATE = 'POSTS_UPDATE'
    ORDERS_LIST = 'ORDERS_LIST'
    ORDERS_LABELS_GET = 'ORDERS_LABELS_GET'
    CONVERSATIONS_INBOX_GET = 'CONVERSATIONS_INBOX_GET'
    CONVERSATIONS_GET = 'CONVERSATIONS_GET'
    CONVERSATIONS_MESSAGES_CREATE = 'CONVERSATIONS_MESSAGES_CREATE'
    CONVERSATIONS_OFFERS_CREATE = 'CONVERSATIONS_OFFERS_CREATE'
    CONVERSATIONS_OFFERS_UPDATE = 'CONVERSATIONS_OFFERS_UPDATE'
