# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
import typing
from .qna_response import QnaResponseParams


class TextAnalyticsResponseParams(typing_extensions.TypedDict):
    request_id: typing_extensions.NotRequired[str]
    answers: typing_extensions.NotRequired[typing.Sequence[QnaResponseParams]]
    """
    List of answers derived from the text analysis. Each answer corresponds to a question from the original request. This field will be null if no valid answers could be generated.
    """
